name:                conduino
version:             0.2.1.0
github:              "mstksg/conduino"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"
tested-with:         GHC >= 8.4 && < 8.10

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Lightweight composable continuation-based stream processors
category:            Control

description: |
  A lightweight continuation-based stream processing library.

  It is similar in nature to pipes and conduit, but useful if you just want
  something quick to manage composable stream processing without focus on IO.

  See README for more information.

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- base >= 4.11 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - containers
  - exceptions
  - free
  - list-transformer
  - mtl
  - transformers

# executables:
#   conduino-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - conduino

# tests:
#   conduino-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - conduino
